#!/data/data/jackpal.androidterm/gentoo/bin/sh
##!/system/bin/sh
##!/data/data/jackpal.androidterm/app_HOME/bin/sh

eprefix="/data/data/jackpal.androidterm/gentoo"
prfx="/sdcard/prfx"
prfx_orig="/data/gentoo"

sed -i -e "s:$prfx_orig:$eprefix:g" "$1" || exit 1

